//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICT2202DigitalForensic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_has_Case
    {
        public int Account_idAccount { get; set; }
        public int Case_idCase { get; set; }
        public string Last_modified { get; set; }
        public string Last_accessed { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Case_Number Case_Number { get; set; }
    }
}
